# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    permissions:
      contents: read
      actions: write

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache/restore@v3
        id: this-cache
        with:
          path: cachedir
          key: this-cache-key

      - name: Display cache
        run: |
          mkdir -p cachedir
          touch cachedir/entry
          cat cachedir/entry

      - name: Add to cache
        run: |
          date >> cachedir/entry

      - name: Remove old cache
        if: steps.this-cache.outputs.cache-hit == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          REPO=${{ github.repository }}
          REF=${{ github.ref }}
          KEY=${{ steps.this-cache.outputs.cache-primary-key }}

          set +e
          echo "Deleting old cache..."
          gh actions-cache delete $KEY -R $REPO -B $REF --confirm
          echo "Done."

      - uses: actions/cache/save@v3
        if: always ()
        with:
          path: cachedir
          key: this-cache-key

  create-artifact:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    steps:
      - name: grab cache
        uses: actions/cache/restore@v3
        with:
          path: cachedir
          key: this-cache-key

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: all-run-date
          path: cachedir
          retention-days: 5
